name: DevOps Cypress Test
on:
  push:
    branches: [master, main]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04  # Usar uma versão específica do Ubuntu
    steps:
      - name: Checkout # Checkout do código
        uses: actions/checkout@v4

      - name: Executar Cypress
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          wait-on: 'http://localhost:3000'
          record: true  # Gravar testes do Cypress
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
