name: DevOps Cypress Test
on:
  push:
    branches: [master, main]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      # Caso algum teste falhe os proximos serao executados
      fail-fast: false
      matrix:
        containers: [1]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true

        #Instala as dependencias
        run:
          npm install

        # Variavel criada configurada no projeto
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}