name: DevOps Cypress Test
on:
  push:
    branches: [master, main]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04  # Usar uma versão específica do Ubuntu
    steps:
      - uses: actions/checkout@v4  # Checkout do código
      - name: Executar Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm start  # Comando para iniciar seu aplicativo
          wait-on: 'http://localhost:3000'
          record: true  # Gravar testes do Cypress
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
